### ISSUE TITLE
填色方塊寛度錯誤

### ISSUE THREAD

**Issue by eight04** [uranusjr/Qelly#85]
測試字元
```
▉
▊
▋
▌
▍
▎
▏
```
PCMan: ![http://i.imgur.com/WCR8UTn.png](http://i.imgur.com/WCR8UTn.png)
Qelly: ![http://i.imgur.com/HdSaaY7.png](http://i.imgur.com/HdSaaY7.png)

**Comment by uranusjr** [comment]
相關程式 https://github.com/uranusjr/Qelly/blob/d532bf6/src/View_p.cpp#L506

應該要除四而不是除八（因為半形字元的寬度 = 4/8 個方塊），笨了 orz

我有空改一下，或是你願意直接送 PR 也歡迎。
